[project]
authors = ["Wishart Torgersrud Consulting"]
entry = "main.sw"
license = "MIT"
name = "token-streaming"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.4.4" }
